for (const path of [
  './file-structure.test.mjs',
  './image-links.test.mjs',
  './migration.test.mjs',
  './access-ui.test.mjs',
  './exif.test.mjs',
  './upload-form.test.mjs',
  './map-style.test.mjs',
  './upload-view.test.mjs',
  './api-shape.test.mjs',
  './telegram.test.mjs',
  './upload-api.test.mjs',
  './original-api.test.mjs',
  './ai-settings-api.test.mjs',
  './ai-preview-api.test.mjs',
  './admin-image-api.test.mjs',
  './image-management-ui.test.mjs',
  './library-view.test.mjs',
  './public-image-view.test.mjs',
  './image-object.test.mjs',
  './random-view.test.mjs',
  './geocode-api.test.mjs',
  './location-search-ui.test.mjs',
  './app-shell.test.mjs',
  './geo-hit.test.mjs',
  './world-boundary-globe.test.mjs',
  './hive-view.test.mjs',
]) {
  await import(path);
}
